In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/ECE324/ECE324 Project 
%cd /content/drive/MyDrive/ECE324 Project

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/ECE324 Project

In [ ]:
import json
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

In [ ]:
df = pd.read_csv("cleanedData.csv", sep='\t')
# df = df.rename(index={0: "stars", 1: "delivery", 2: "takeout", 3: "outdoor seating", 4: "closingTime", 5: "cost", 6: "cuisine", 7: "location"})
df

,stars,delivery,takeout,Outdoor seating,hours,cost,location,cuisine
0,4.0,0,0,0,15.0,2,0,4
1,4.5,0,0,0,22.0,2,0,43
2,4.5,0,0,0,21.0,2,0,152
3,4.5,0,0,0,16.0,2,0,72
4,4.0,0,0,0,14.5,2,0,4
...,...,...,...,...,...,...,...,...
1025,3.5,0,0,0,22.0,2,2,41
1026,4.0,0,0,0,21.5,2,2,46
1027,3.0,0,0,0,23.0,2,2,14
1028,4.0,0,0,0,16.0,1,2,91
1029,4.0,0,0,0,18.0,1,2,39

In [ ]:
# Perform train-test split
Y_col = 'stars'
X_cols = df.loc[:, df.columns != Y_col].columns
X_train, X_test, y_train, y_test = train_test_split(
    df[X_cols], df[Y_col],test_size=0.1, random_state=42)
y_train = list(y_train)
y_test = list(y_test)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
xgboost=XGBClassifier()
xgboost.fit(X_train,to_categorical(y_train))
xgboost.score(X_test, to_categorical(y_test))

In [ ]:
model = GradientBoostingClassifier(
    n_estimators=100, learning_rate=1, max_depth=1, random_state=42)

str_y_train = list(map(str, y_train))
str_y_test = list(map(str, y_test))

model.fit(X_train, (str_y_train))
model.score(X_test, (str_y_test))

0.33980582524271846